//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookServicePrestitoSelfHost
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/Esercitazione.Library.Entities")]
    public partial class Book : object
    {
        
        private string AutoreField;
        
        private string ISBNField;
        
        private string SommarioField;
        
        private string TitoloField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Autore
        {
            get
            {
                return this.AutoreField;
            }
            set
            {
                this.AutoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISBN
        {
            get
            {
                return this.ISBNField;
            }
            set
            {
                this.ISBNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sommario
        {
            get
            {
                return this.SommarioField;
            }
            set
            {
                this.SommarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titolo
        {
            get
            {
                return this.TitoloField;
            }
            set
            {
                this.TitoloField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Prestito", Namespace="http://schemas.datacontract.org/2004/07/Esercitazione.CoreLibrary.Entities")]
    public partial class Prestito : object
    {
        
        private System.DateTime DataPrestitoField;
        
        private System.Nullable<System.DateTime> DataResoField;
        
        private string IdField;
        
        private string IdLibroField;
        
        private string UtenteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataPrestito
        {
            get
            {
                return this.DataPrestitoField;
            }
            set
            {
                this.DataPrestitoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataReso
        {
            get
            {
                return this.DataResoField;
            }
            set
            {
                this.DataResoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdLibro
        {
            get
            {
                return this.IdLibroField;
            }
            set
            {
                this.IdLibroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Utente
        {
            get
            {
                return this.UtenteField;
            }
            set
            {
                this.UtenteField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BookServicePrestitoSelfHost.IBookService")]
    public interface IBookService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/AddBook", ReplyAction="http://tempuri.org/IBookService/AddBookResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ArgumentNullException), Action="http://tempuri.org/IBookService/AddBookArgumentNullExceptionFault", Name="ArgumentNullException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        bool AddBook(BookServicePrestitoSelfHost.Book newBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/AddBook", ReplyAction="http://tempuri.org/IBookService/AddBookResponse")]
        System.Threading.Tasks.Task<bool> AddBookAsync(BookServicePrestitoSelfHost.Book newBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/DeleteBook", ReplyAction="http://tempuri.org/IBookService/DeleteBookResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ArgumentNullException), Action="http://tempuri.org/IBookService/DeleteBookArgumentNullExceptionFault", Name="ArgumentNullException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        bool DeleteBook(BookServicePrestitoSelfHost.Book newBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/DeleteBook", ReplyAction="http://tempuri.org/IBookService/DeleteBookResponse")]
        System.Threading.Tasks.Task<bool> DeleteBookAsync(BookServicePrestitoSelfHost.Book newBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/UpdateBook", ReplyAction="http://tempuri.org/IBookService/UpdateBookResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ArgumentNullException), Action="http://tempuri.org/IBookService/UpdateBookArgumentNullExceptionFault", Name="ArgumentNullException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        bool UpdateBook(BookServicePrestitoSelfHost.Book newBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/UpdateBook", ReplyAction="http://tempuri.org/IBookService/UpdateBookResponse")]
        System.Threading.Tasks.Task<bool> UpdateBookAsync(BookServicePrestitoSelfHost.Book newBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetAllBooks", ReplyAction="http://tempuri.org/IBookService/GetAllBooksResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ArgumentNullException), Action="http://tempuri.org/IBookService/GetAllBooksArgumentNullExceptionFault", Name="ArgumentNullException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Collections.Generic.List<BookServicePrestitoSelfHost.Book> GetAllBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetAllBooks", ReplyAction="http://tempuri.org/IBookService/GetAllBooksResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BookServicePrestitoSelfHost.Book>> GetAllBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/PrestitoLibro", ReplyAction="http://tempuri.org/IBookService/PrestitoLibroResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ArgumentNullException), Action="http://tempuri.org/IBookService/PrestitoLibroArgumentNullExceptionFault", Name="ArgumentNullException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        BookServicePrestitoSelfHost.Prestito PrestitoLibro(BookServicePrestitoSelfHost.Book bookDaPrestare);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/PrestitoLibro", ReplyAction="http://tempuri.org/IBookService/PrestitoLibroResponse")]
        System.Threading.Tasks.Task<BookServicePrestitoSelfHost.Prestito> PrestitoLibroAsync(BookServicePrestitoSelfHost.Book bookDaPrestare);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/ResaLibro", ReplyAction="http://tempuri.org/IBookService/ResaLibroResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ArgumentNullException), Action="http://tempuri.org/IBookService/ResaLibroArgumentNullExceptionFault", Name="ArgumentNullException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        BookServicePrestitoSelfHost.Prestito ResaLibro(BookServicePrestitoSelfHost.Prestito pres, BookServicePrestitoSelfHost.Book bookDaRestituire);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/ResaLibro", ReplyAction="http://tempuri.org/IBookService/ResaLibroResponse")]
        System.Threading.Tasks.Task<BookServicePrestitoSelfHost.Prestito> ResaLibroAsync(BookServicePrestitoSelfHost.Prestito pres, BookServicePrestitoSelfHost.Book bookDaRestituire);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetAllPrestiti", ReplyAction="http://tempuri.org/IBookService/GetAllPrestitiResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ArgumentNullException), Action="http://tempuri.org/IBookService/GetAllPrestitiArgumentNullExceptionFault", Name="ArgumentNullException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Collections.Generic.List<BookServicePrestitoSelfHost.Prestito> GetAllPrestiti();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetAllPrestiti", ReplyAction="http://tempuri.org/IBookService/GetAllPrestitiResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BookServicePrestitoSelfHost.Prestito>> GetAllPrestitiAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IBookServiceChannel : BookServicePrestitoSelfHost.IBookService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class BookServiceClient : System.ServiceModel.ClientBase<BookServicePrestitoSelfHost.IBookService>, BookServicePrestitoSelfHost.IBookService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BookServiceClient() : 
                base(BookServiceClient.GetDefaultBinding(), BookServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IBookService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BookServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(BookServiceClient.GetBindingForEndpoint(endpointConfiguration), BookServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BookServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BookServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BookServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BookServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BookServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public bool AddBook(BookServicePrestitoSelfHost.Book newBook)
        {
            return base.Channel.AddBook(newBook);
        }
        
        public System.Threading.Tasks.Task<bool> AddBookAsync(BookServicePrestitoSelfHost.Book newBook)
        {
            return base.Channel.AddBookAsync(newBook);
        }
        
        public bool DeleteBook(BookServicePrestitoSelfHost.Book newBook)
        {
            return base.Channel.DeleteBook(newBook);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteBookAsync(BookServicePrestitoSelfHost.Book newBook)
        {
            return base.Channel.DeleteBookAsync(newBook);
        }
        
        public bool UpdateBook(BookServicePrestitoSelfHost.Book newBook)
        {
            return base.Channel.UpdateBook(newBook);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateBookAsync(BookServicePrestitoSelfHost.Book newBook)
        {
            return base.Channel.UpdateBookAsync(newBook);
        }
        
        public System.Collections.Generic.List<BookServicePrestitoSelfHost.Book> GetAllBooks()
        {
            return base.Channel.GetAllBooks();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BookServicePrestitoSelfHost.Book>> GetAllBooksAsync()
        {
            return base.Channel.GetAllBooksAsync();
        }
        
        public BookServicePrestitoSelfHost.Prestito PrestitoLibro(BookServicePrestitoSelfHost.Book bookDaPrestare)
        {
            return base.Channel.PrestitoLibro(bookDaPrestare);
        }
        
        public System.Threading.Tasks.Task<BookServicePrestitoSelfHost.Prestito> PrestitoLibroAsync(BookServicePrestitoSelfHost.Book bookDaPrestare)
        {
            return base.Channel.PrestitoLibroAsync(bookDaPrestare);
        }
        
        public BookServicePrestitoSelfHost.Prestito ResaLibro(BookServicePrestitoSelfHost.Prestito pres, BookServicePrestitoSelfHost.Book bookDaRestituire)
        {
            return base.Channel.ResaLibro(pres, bookDaRestituire);
        }
        
        public System.Threading.Tasks.Task<BookServicePrestitoSelfHost.Prestito> ResaLibroAsync(BookServicePrestitoSelfHost.Prestito pres, BookServicePrestitoSelfHost.Book bookDaRestituire)
        {
            return base.Channel.ResaLibroAsync(pres, bookDaRestituire);
        }
        
        public System.Collections.Generic.List<BookServicePrestitoSelfHost.Prestito> GetAllPrestiti()
        {
            return base.Channel.GetAllPrestiti();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BookServicePrestitoSelfHost.Prestito>> GetAllPrestitiAsync()
        {
            return base.Channel.GetAllPrestitiAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IBookService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IBookService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/Esercitazione.WCFService/BookService/" +
                        "");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return BookServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IBookService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return BookServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IBookService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IBookService,
        }
    }
}
